---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

cache:
  directories:
    - /tmp/liftoff

matrix:
  include:
    - env: DIST=loki
    - env: DIST=juno

before_install:
  - docker pull ubuntu:16.04
  - sudo apt-get install rustc cargo
  - sudo apt-get install libssl-dev pkgconf libpng16-dev
  - sudo apt-get insatll libnotify-dev libgtk-3-dev libjson-glib-dev
  
install:
  - npm install @elementaryos/houston
  
script:
  - houston ci
    --name-appstream com.github.arshubham.srtnr.desktop
    --name-domain com.github.arshubham.srtnr
    --name-human srtnr
    --distribution $DIST
