[package]
name = "srtnr-gtk"
version = "0.1.0"
authors = ["Shubham Arora <shubhamarora@protonmail.com>"]
workspace = "../"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_18"]

[dependencies]
gio = "0.3.0"
urlshortener = "0.8.0"
